//
// Created by ajahueym on 06/09/20.
//

#ifndef MICRODRONEFIRMWARE_SIMCOMMSUPDATETASK_H
#define MICRODRONEFIRMWARE_TOFUPDATETASK_H

_Noreturn void TOFUpdate_Task(void *pvParameters);

#endif //MICRODRONEFIRMWARE_SIMCOMMSUPDATETASK_H
