//
// Created by abiel on 9/6/20.
//

#ifndef MICRODRONEFIRMWARE_CONFIG_H
#define MICRODRONEFIRMWARE_CONFIG_H

#include "FreeRTOS.h"

const TickType_t ATTITUDE_CONTROLLER_WAIT_TIME = pdMS_TO_TICKS(1);

#endif //MICRODRONEFIRMWARE_CONFIG_H
