//
// Created by abiel on 9/6/20.
//

#ifndef MICRODRONEFIRMWARE_ATTITUDECONTROLLERTASK_H
#define MICRODRONEFIRMWARE_ATTITUDECONTROLLERTASK_H

_Noreturn void AttitudeController_Task(void *pvParameters);

#endif //MICRODRONEFIRMWARE_ATTITUDECONTROLLERTASK_H
